"""
Django settings for nostra project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-htx^3+2pq*iuxr6js!9hyutg96qdmu=i&cu)8u^8-&(8!*f$8c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Shop',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nostra.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [BASE_DIR/'Shop/templates'],
        'DIRS': [os.path.join(BASE_DIR, 'Shop', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nostra.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'nostra_db',
        'USER': 'nirmalkumar',
        'PASSWORD':'nostra@321',
        'HOST': 'localhost',
        'PORT':'3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR/"Shop/static"]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Stripe API keys from your Stripe dashboard

# STRIPE_PUBLIC_KEY = 'your-stripe-public-key-here'
# STRIPE_SECRET_KEY = 'your-stripe-secret-key-here'

LOGIN_REDIRECT_URL = '/'  # Where to go after login
LOGOUT_REDIRECT_URL = '/'  # Where to go after logout

# US Nostra Demo App
PAYPAL_CLIENT_ID = 'AQrJmXNtVrL1Unh3gXDqg4hoxX52-B5wDaqTkQoTylArKXefsiBLiDFYud_Wgz-_08SoLU2MgXuaCc9e'
PAYPAL_CLIENT_SECRET = 'ENXmXe_NdCGPCziyqhxfp-eePbLW2tJJEr-mVziFe5948lQe-1Irea2NfHvSjlAG8bVM63J2AYAN66Rt'

# IND Nostra
# PAYPAL_CLIENT_ID = 'Adyt2Z19Yl_S6QH-Vl4XmOX_4Axw7zGgSm1O94NimbaN84jOow5Zi7Nh0EKbrIc65zDaveSIp7dNx6-P'
# PAYPAL_CLIENT_SECRET = 'ED98oW5kvg-KJdtJ9BnxXEcMNKHRBHdvXLrlePK-TZMjso-o61VaIUnY0vzuAUOpm1Om2OORMDfL6UJn'

# IND Default
# PAYPAL_CLIENT_ID = 'AdAdvbSiNJwuOIAF1-ZAyeoXM_DUFxRv2DPS-8u5yYm1l39SjG1MiMCvt4-44W5tHH5OtBsql-xsZEwj'
# PAYPAL_CLIENT_SECRET = 'ECLoklf6lU0NHhaiBucmF1El8NI_WdsuALmAA_ucrQN6JsI_D1QG3p9T0ugO_bqeUvlxny9na-eOrbpg'
